spring:
  sql:
    init:
      mode: always
  banner:
    location: classpath:/customerMS/src/main/resources/bannername.txt
  datasource:
    driver-class-name: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:customerDB
    username: admin
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
